default:

  app_name: "Clinical Patient Viewer"

  data_source: "mock"

dev:
# 
 
  database: "dev_db"

  log_level: "DEBUG"

qa:

  database: "qa_db"

  log_level: "INFO"

prod:

  database: "prod_db"

  log_level: "WARN"